quarkus:
  jackson:
    serialization-inclusion: non-empty

"%prod":
  quarkus:
    datasource:
      username: fruits
      password: fruits
      jdbc:
        url: jdbc:postgresql://localhost:5432/fruits
